# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения 
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest

    steps:
      # ШАГ №1. Получаем код из репозитория
      - uses: actions/checkout@v3

      # ШАГ №2. Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          # Команды выполняемые на сервере
          # | - многострочный литерал это означает команды будут выполняться в shell по очереди
          script: |
            # Переходим в директорию проекта
            cd /home/v/python_417_django_htmx

            # Останавливаем службу приложения  (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop django_417_gunicorn

            # Обновляем код из репозитория (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | git pull

            # Если у вас PIP
            # Активируем виртуальное окружение
            source venv/bin/activate

            # Обновляем зависимости
            pip install -r requirements.txt

            # Обновляем схему базы данных
            python3 manage.py migrate

            # Собираем статику
            python3 manage.py collectstatic --noinput

            # Если у вас Poetry
            # /home/v/.local/bin/poetry install --no-root

            # Создаем файл .env из отдельных секретов
            echo "TELEGRAM_BOT_KEY=${{ secrets.TELEGRAM_BOT_KEY }}" > .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "DEBUG_MODE=${{ secrets.DEBUG_MODE }}" >> .env

            # Перезапускаем systemd сервис (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start django_417_gunicorn
